const KEY="rocketTrackerDataV1";
const sample={courses:[{id:1,code:"IT 1010",name:"Introduction to Information Technology",credits:3,status:"current",grade:92,days:"Mon, Wed",time:"10:00 AM",location:"Main Campus"},{id:2,code:"MATH 1200",name:"College Mathematics",credits:3,status:"current",grade:86,days:"Tue, Thu",time:"11:00 AM",location:"Main Campus"},{id:3,code:"ENGL 1110",name:"English Composition",credits:3,status:"current",grade:95,days:"Friday",time:"1:00 PM",location:"Main Campus"}],assignments:[{id:11,title:"Technology Reflection",course:"IT 1010",due:"2026-09-08",points:50,status:"upcoming"},{id:12,title:"Practice Set 1",course:"MATH 1200",due:"2026-09-10",points:40,status:"upcoming"},{id:13,title:"Reading Response",course:"ENGL 1110",due:"2026-09-12",points:25,status:"upcoming"}],attendance:{1:{attended:8,missed:1},2:{attended:9,missed:0},3:{attended:4,missed:1}},exams:[{id:21,title:"Math Quiz 1",course:"MATH 1200",date:"2026-09-17"}],goals:[{id:31,title:"Maintain a 3.5 GPA",target:100,progress:70},{id:32,title:"Submit every assignment on time",target:100,progress:60}],notes:"Welcome to Rocket Tracker!\n\nUse this space for study notes and reminders.",theme:"light"};
let data=load(), courseFilter="all",assignmentFilter="all";
function load(){try{return JSON.parse(localStorage.getItem(KEY))||structuredClone(sample)}catch{return structuredClone(sample)}}
function save(){localStorage.setItem(KEY,JSON.stringify(data));renderAll()}
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
function toast(msg){const t=$("#toast");t.textContent=msg;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),1800)}
function letter(n){return n>=93?"A":n>=90?"A−":n>=87?"B+":n>=83?"B":n>=80?"B−":n>=77?"C+":n>=73?"C":n>=70?"C−":n>=67?"D+":n>=63?"D":n>=60?"D−":"F"}
function gp(n){return n>=93?4:n>=90?3.7:n>=87?3.3:n>=83?3:n>=80?2.7:n>=77?2.3:n>=73?2:n>=70?1.7:n>=67?1.3:n>=63?1:n>=60?.7:0}
function gpa(){let c=0,p=0;data.courses.filter(x=>x.status!=="planned").forEach(x=>{c+=+x.credits;p+=gp(+x.grade)*+x.credits});return c?(p/c).toFixed(2):"0.00"}
function attendancePct(a){const total=a.attended+a.missed;return total?Math.round(a.attended/total*100):100}
function globalAttendance(){const vals=data.courses.map(c=>data.attendance[c.id]||{attended:0,missed:0});let a=0,m=0;vals.forEach(x=>{a+=x.attended;m+=x.missed});return a+m?Math.round(a/(a+m)*100):100}
function setPage(name){$$('.page').forEach(x=>x.classList.toggle('active',x.id===name+'-page'));$$('.nav-link').forEach(x=>x.classList.toggle('active',x.dataset.page===name));$('#page-title').textContent=$(`[data-page="${name}"] span`).textContent;location.hash=name;$('#sidebar').classList.remove('open')}
$$('.nav-link').forEach(b=>b.onclick=()=>setPage(b.dataset.page));$$('[data-open]').forEach(b=>b.onclick=()=>setPage(b.dataset.open));$('#mobile-menu').onclick=()=>$('#sidebar').classList.toggle('open');
function stat(label,value,sub){return `<article class="stat"><span>${esc(label)}</span><b>${esc(value)}</b><span>${esc(sub)}</span></article>`}
function summary(label,value,sub){return `<article class="summary"><span>${esc(label)}</span><b>${esc(value)}</b><span>${esc(sub)}</span></article>`}
function renderDashboard(){const pending=data.assignments.filter(a=>a.status!=="completed").length;$('#dashboard-stats').innerHTML=stat('Semester GPA',gpa(),'Estimated')+stat('Assignments',pending,'Not completed')+stat('Attendance',globalAttendance()+'%','All courses')+stat('Goals',data.goals.length,'Active targets');$('#dashboard-courses').innerHTML=data.courses.filter(c=>c.status==='current').slice(0,4).map(c=>`<div class="list-row"><div><b>${esc(c.code)} · ${esc(c.name)}</b><small>${c.credits} credits · ${esc(c.days)}</small></div><b>${letter(c.grade)} · ${c.grade}%</b></div>`).join('')||'<div class="empty">No current courses.</div>';$('#dashboard-deadlines').innerHTML=data.assignments.filter(a=>a.status!=="completed").sort((a,b)=>a.due.localeCompare(b.due)).slice(0,5).map(a=>`<div class="list-row"><div><b>${esc(a.title)}</b><small>${esc(a.course)}</small></div><b>${esc(a.due)}</b></div>`).join('')||'<div class="empty">No upcoming work.</div>'}
function renderCourses(){const q=$('#course-search').value.toLowerCase();const list=data.courses.filter(c=>(courseFilter==='all'||c.status===courseFilter)&&(c.name+' '+c.code).toLowerCase().includes(q));const credits=data.courses.filter(c=>c.status==='current').reduce((s,c)=>s+(+c.credits),0);$('#course-summary').innerHTML=summary('Total Courses',data.courses.length,'All statuses')+summary('Credits Enrolled',credits,'Current courses')+summary('Semester GPA',gpa(),'Estimated')+summary('Course Load',credits>=12?'Full-time':'Part-time',credits+' credits');$('#course-grid').innerHTML=list.map(c=>`<article class="course-card"><div class="course-head"><span class="badge">${esc(c.status)}</span><b>${esc(c.code)}</b></div><h3>${esc(c.name)}</h3><div class="meta"><span>📍 ${esc(c.location)}</span><span>🕘 ${esc(c.days)} · ${esc(c.time)}</span><span>🎓 ${c.credits} credit hours</span></div><div class="course-head"><span>Grade: <b>${letter(c.grade)}</b></span><b>${c.grade}%</b></div><div class="progress"><i style="width:${Math.max(0,Math.min(100,c.grade))}%"></i></div><div class="card-actions"><button class="secondary" onclick="editCourse(${c.id})">Edit</button><button class="delete" onclick="removeItem('courses',${c.id})">Delete</button></div></article>`).join('')||'<div class="panel empty">No courses found.</div>'}
function computedStatus(a){if(a.status==='completed')return 'completed';const today=new Date().toISOString().slice(0,10);return a.due<today?'overdue':'upcoming'}
function renderAssignments(){const q=$('#assignment-search').value.toLowerCase();const list=data.assignments.filter(a=>{const s=computedStatus(a);return (assignmentFilter==='all'||s===assignmentFilter)&&(a.title+' '+a.course).toLowerCase().includes(q)});const complete=data.assignments.filter(a=>a.status==='completed').length, overdue=data.assignments.filter(a=>computedStatus(a)==='overdue').length;$('#assignment-summary').innerHTML=summary('Total',data.assignments.length,'All assignments')+summary('Upcoming',data.assignments.length-complete-overdue,'Not yet due')+summary('Completed',complete,'Finished')+summary('Overdue',overdue,'Needs attention');$('#assignment-table').innerHTML=list.map(a=>{const s=computedStatus(a);return `<tr><td><b>${esc(a.title)}</b></td><td>${esc(a.course)}</td><td>${esc(a.due)}</td><td>${a.points}</td><td class="status-${s}">${s}</td><td><button class="secondary" onclick="toggleAssignment(${a.id})">${a.status==='completed'?'Reopen':'Complete'}</button> <button class="delete" onclick="removeItem('assignments',${a.id})">×</button></td></tr>`}).join('')||'<tr><td colspan="6" class="empty">No assignments found.</td></tr>'}
function renderGrades(){const credits=data.courses.reduce((s,c)=>s+(+c.credits),0);$('#grade-summary').innerHTML=summary('Semester GPA',gpa(),'Estimated')+summary('Credits',credits,'Tracked')+summary('Highest Grade',data.courses.length?Math.max(...data.courses.map(c=>+c.grade))+'%':'—','Current best')+summary('Academic Standing',+gpa()>=2?'Good':'Review','Prototype estimate');$('#grade-table').innerHTML=data.courses.map(c=>`<tr><td><b>${esc(c.code)}</b><br>${esc(c.name)}</td><td>${c.credits}</td><td>${c.grade}%</td><td><b>${letter(c.grade)}</b></td><td>${gp(c.grade).toFixed(1)}</td></tr>`).join('')}
function renderAttendance(){let attended=0,missed=0;data.courses.forEach(c=>{const a=data.attendance[c.id]||{attended:0,missed:0};attended+=a.attended;missed+=a.missed});$('#attendance-summary').innerHTML=summary('Overall',globalAttendance()+'%','Attendance rate')+summary('Attended',attended,'Meetings')+summary('Missed',missed,'Meetings')+summary('Tracked Courses',data.courses.length,'Total');$('#attendance-grid').innerHTML=data.courses.map(c=>{const a=data.attendance[c.id]||{attended:0,missed:0},p=attendancePct(a);return `<article class="attendance-card"><span class="badge">${esc(c.code)}</span><h3>${esc(c.name)}</h3><p>${a.attended} attended · ${a.missed} missed</p><div class="course-head"><span>Attendance</span><b>${p}%</b></div><div class="progress"><i style="width:${p}%;background:${p<75?'var(--red)':'var(--green)'}"></i></div></article>`}).join('')||'<div class="panel empty">Add a course first.</div>'}
function renderSchedule(){$('#schedule-list').innerHTML=data.courses.filter(c=>c.status==='current').map(c=>`<div class="list-row"><div><b>${esc(c.code)} · ${esc(c.name)}</b><small>${esc(c.location)}</small></div><div><b>${esc(c.days)}</b><small>${esc(c.time)}</small></div></div>`).join('')||'<div class="empty">No scheduled courses.</div>'}
function renderExams(){$('#exam-list').innerHTML=data.exams.map(x=>`<div class="list-row"><div><b>${esc(x.title)}</b><small>${esc(x.course)}</small></div><div><b>${esc(x.date)}</b> <button class="delete" onclick="removeItem('exams',${x.id})">×</button></div></div>`).join('')||'<div class="empty">No exams added.</div>'}
function renderGoals(){$('#goal-grid').innerHTML=data.goals.map(g=>`<article class="goal-card"><span class="badge">Goal</span><h3>${esc(g.title)}</h3><div class="course-head"><span>Progress</span><b>${g.progress}%</b></div><div class="progress"><i style="width:${g.progress}%;background:var(--purple)"></i></div><div class="card-actions"><button class="delete" onclick="removeItem('goals',${g.id})">Delete</button></div></article>`).join('')||'<div class="panel empty">No goals added.</div>'}
function renderAll(){renderDashboard();renderCourses();renderAssignments();renderGrades();renderAttendance();renderSchedule();renderExams();renderGoals();if(document.activeElement!==$('#notes'))$('#notes').value=data.notes||'';document.body.classList.toggle('dark',data.theme==='dark')}
$('#course-search').oninput=renderCourses;$('#assignment-search').oninput=renderAssignments;$$('#course-filters button').forEach(b=>b.onclick=()=>{$$('#course-filters button').forEach(x=>x.classList.remove('active'));b.classList.add('active');courseFilter=b.dataset.filter;renderCourses()});$$('#assignment-filters button').forEach(b=>b.onclick=()=>{$$('#assignment-filters button').forEach(x=>x.classList.remove('active'));b.classList.add('active');assignmentFilter=b.dataset.filter;renderAssignments()});
$('#notes').oninput=e=>{data.notes=e.target.value;localStorage.setItem(KEY,JSON.stringify(data))};
function removeItem(type,id){if(!confirm('Delete this item?'))return;data[type]=data[type].filter(x=>x.id!==id);if(type==='courses')delete data.attendance[id];save();toast('Deleted')}
function toggleAssignment(id){const a=data.assignments.find(x=>x.id===id);a.status=a.status==='completed'?'upcoming':'completed';save();toast('Assignment updated')}
const modal=$('#modal'), fields=$('#modal-fields'), form=$('#modal-form');let modalType='',editingId=null;
const schemas={course:[['code','Course code','text'],['name','Course name','text'],['credits','Credits','number'],['status','Status','select','current|planned|completed'],['grade','Percentage','number'],['days','Meeting days','text'],['time','Time','time'],['location','Location','text']],assignment:[['title','Assignment title','text'],['course','Course code','text'],['due','Due date','date'],['points','Points','number']],attendance:[['courseId','Course','course'],['result','Result','select','attended|missed']],exam:[['title','Exam title','text'],['course','Course code','text'],['date','Date','date']],goal:[['title','Goal','text'],['progress','Progress percent','number']]};
function fieldHtml(f,val=''){const [name,label,type,options]=f;if(type==='select')return `<div class="field"><label>${label}</label><select name="${name}">${options.split('|').map(x=>`<option ${x===val?'selected':''}>${x}</option>`).join('')}</select></div>`;if(type==='course')return `<div class="field"><label>${label}</label><select name="${name}">${data.courses.map(c=>`<option value="${c.id}">${esc(c.code)} · ${esc(c.name)}</option>`).join('')}</select></div>`;return `<div class="field"><label>${label}</label><input required name="${name}" type="${type}" value="${esc(val)}" ${type==='number'?'min="0"':''}></div>`}
function openModal(type,item=null){modalType=type;editingId=item?.id||null;$('#modal-title').textContent=(item?'Edit ':'Add ')+type[0].toUpperCase()+type.slice(1);fields.innerHTML=schemas[type].map(f=>fieldHtml(f,item?.[f[0]]??'')).join('');modal.showModal()}
$$('[data-modal]').forEach(b=>b.onclick=()=>openModal(b.dataset.modal));
window.editCourse=id=>openModal('course',data.courses.find(c=>c.id===id));window.removeItem=removeItem;window.toggleAssignment=toggleAssignment;
form.addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return;e.preventDefault();const v=Object.fromEntries(new FormData(form));if(modalType==='attendance'){const id=+v.courseId;data.attendance[id]??={attended:0,missed:0};data.attendance[id][v.result]++;}else{const map={course:'courses',assignment:'assignments',exam:'exams',goal:'goals'},arr=data[map[modalType]];const item={...v,id:editingId||Date.now()};['credits','grade','points','progress'].forEach(k=>{if(k in item)item[k]=+item[k]});if(modalType==='assignment')item.status='upcoming';if(editingId){const i=arr.findIndex(x=>x.id===editingId);arr[i]=item}else arr.push(item)}modal.close();save();toast('Saved')});
function toggleTheme(){data.theme=data.theme==='dark'?'light':'dark';save()}$('#theme-toggle').onclick=toggleTheme;$('#settings-theme').onclick=toggleTheme;
$('#export-data').onclick=()=>{const b=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='rocket-tracker-backup.json';a.click();URL.revokeObjectURL(a.href)};
$('#import-data').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{data=JSON.parse(r.result);save();toast('Backup imported')}catch{alert('That file is not a valid tracker backup.')}};r.readAsText(f)};
$('#reset-data').onclick=()=>{if(confirm('Reset all local tracker data?')){data=structuredClone(sample);save();toast('Prototype reset')}};
const start=location.hash.slice(1);if(start&&$(`#${start}-page`))setPage(start);renderAll();