const KEY="rocketTrackerDataV1";
const sample={courses:[{id:1,code:"IT 1010",name:"Introduction to Information Technology",credits:3,status:"current",grade:92,days:"Mon, Wed",time:"10:00 AM",location:"Main Campus"},{id:2,code:"MATH 1200",name:"College Mathematics",credits:3,status:"current",grade:86,days:"Tue, Thu",time:"11:00 AM",location:"Main Campus"},{id:3,code:"ENGL 1110",name:"English Composition",credits:3,status:"current",grade:95,days:"Friday",time:"1:00 PM",location:"Main Campus"}],assignments:[{id:11,title:"Technology Reflection",course:"IT 1010",due:"2026-09-08",points:50,status:"upcoming"},{id:12,title:"Practice Set 1",course:"MATH 1200",due:"2026-09-10",points:40,status:"upcoming"},{id:13,title:"Reading Response",course:"ENGL 1110",due:"2026-09-12",points:25,status:"upcoming"}],attendance:{1:{attended:8,missed:1},2:{attended:9,missed:0},3:{attended:4,missed:1}},exams:[{id:21,title:"Math Quiz 1",course:"MATH 1200",date:"2026-09-17"}],goals:[{id:31,title:"Maintain a 3.5 GPA",target:100,progress:70},{id:32,title:"Submit every assignment on time",target:100,progress:60}],notes:"Welcome to Rocket Tracker!\n\nUse this space for study notes and reminders.",theme:"light",studySessions:[{id:41,course:"IT 1010",date:"2026-09-03",minutes:75,method:"Focused review",topic:"Computer systems"},{id:42,course:"MATH 1200",date:"2026-09-04",minutes:50,method:"Practice problems",topic:"Functions"}],requirements:[{id:51,title:"General Education",category:"Core",credits:30,completed:9},{id:52,title:"Major Requirements",category:"Major",credits:45,completed:0},{id:53,title:"Electives",category:"Elective",credits:15,completed:0}],degreeCredits:120,events:[{id:61,title:"Welcome Week Activity",date:"2026-08-30",type:"personal",location:"Main Campus",notes:"Replace this sample with the event details you plan to attend."}],academicDates:[
{id:"ut-f26-start",title:"First Day of Fall Classes",date:"2026-08-31",type:"academic",category:"Classes"},
{id:"ut-labor-26",title:"Labor Day — No Classes",date:"2026-09-07",type:"academic",category:"Holiday"},
{id:"ut-fallbreak1-26",title:"Fall Break",date:"2026-10-19",type:"academic",category:"Break"},
{id:"ut-fallbreak2-26",title:"Fall Break",date:"2026-10-20",type:"academic",category:"Break"},
{id:"ut-veterans-26",title:"Veterans Day — No Classes",date:"2026-11-11",type:"academic",category:"Holiday"},
{id:"ut-noclass-26",title:"No Classes (COMLS-MD in session)",date:"2026-11-25",type:"academic",category:"No Classes"},
{id:"ut-thanks1-26",title:"Thanksgiving Break",date:"2026-11-26",type:"academic",category:"Break"},
{id:"ut-thanks2-26",title:"Thanksgiving Break",date:"2026-11-27",type:"academic",category:"Break"},
{id:"ut-f26-last",title:"Last Day of Fall Classes",date:"2026-12-11",type:"academic",category:"Classes"},
{id:"ut-f26-final1",title:"Fall Final Exam Week Begins",date:"2026-12-14",type:"academic",category:"Finals"},
{id:"ut-f26-final2",title:"Fall Final Exam Week Ends",date:"2026-12-18",type:"academic",category:"Finals"},
{id:"ut-f26-grad",title:"Fall University Commencement",date:"2026-12-19",type:"academic",category:"Commencement"},
{id:"ut-winter-start",title:"Winter Break Begins",date:"2026-12-24",type:"academic",category:"Break"},
{id:"ut-winter-end",title:"Winter Break Ends",date:"2027-01-03",type:"academic",category:"Break"},
{id:"ut-mlk-27",title:"Martin Luther King Jr. Day — No Classes",date:"2027-01-18",type:"academic",category:"Holiday"},
{id:"ut-s27-start",title:"First Day of Spring Classes",date:"2027-01-19",type:"academic",category:"Classes"},
{id:"ut-springbreak-start",title:"Spring Break Begins",date:"2027-03-08",type:"academic",category:"Break"},
{id:"ut-springbreak-end",title:"Spring Break Ends",date:"2027-03-12",type:"academic",category:"Break"},
{id:"ut-s27-last",title:"Last Day of Spring Classes",date:"2027-04-30",type:"academic",category:"Classes"},
{id:"ut-s27-finals-start",title:"Spring Final Exam Week Begins",date:"2027-05-03",type:"academic",category:"Finals"},
{id:"ut-s27-finals-end",title:"Spring Final Exam Week Ends",date:"2027-05-07",type:"academic",category:"Finals"},
{id:"ut-s27-grad",title:"Spring University Commencement",date:"2027-05-08",type:"academic",category:"Commencement"},
{id:"ut-summer1-27",title:"POT 1 and Summer Session I Begin",date:"2027-05-17",type:"academic",category:"Summer"},
{id:"ut-memorial-27",title:"Memorial Day — No Classes",date:"2027-05-31",type:"academic",category:"Holiday"},
{id:"ut-summer3-27",title:"Summer Session III Begins",date:"2027-06-14",type:"academic",category:"Summer"},
{id:"ut-juneteenth-27",title:"Juneteenth Observed — No Classes",date:"2027-06-18",type:"academic",category:"Holiday"},
{id:"ut-summer1-end-27",title:"Summer Session I Ends",date:"2027-06-25",type:"academic",category:"Summer"},
{id:"ut-summer2-27",title:"Summer Session II Begins",date:"2027-06-28",type:"academic",category:"Summer"},
{id:"ut-independence-27",title:"Independence Day Observed — No Classes",date:"2027-07-05",type:"academic",category:"Holiday"},
{id:"ut-summer-end-27",title:"POT 1 and Summer Sessions II and III End",date:"2027-08-06",type:"academic",category:"Summer"}
]};
let data=load(), courseFilter="all",assignmentFilter="all";
data.studySessions ||= [];
data.requirements ||= [];
data.degreeCredits ||= 120;
data.events ||= [];
data.academicDates ||= structuredClone(sample.academicDates);
data.profile ||= {name:'Caleb',school:'University of Toledo',program:'Exploratory Studies',picture:''};
data.semesters ||= [
{id:'fall-2025',name:'Fall 2025',start:'2025-08-25',end:'2025-12-13'},
{id:'spring-2026',name:'Spring 2026',start:'2026-01-12',end:'2026-05-02'},
{id:'summer-2026',name:'Summer 2026',start:'2026-05-11',end:'2026-08-21'},
{id:'fall-2026',name:'Fall 2026',start:'2026-08-31',end:'2026-12-19'},
{id:'spring-2027',name:'Spring 2027',start:'2027-01-18',end:'2027-05-08'},
{id:'summer-2027',name:'Summer 2027',start:'2027-05-17',end:'2027-08-06'}
];
const courseColors=['#176bd6','#f1a800','#159a63','#7650c7','#d94d67','#0097a7'];
function load(){try{return JSON.parse(localStorage.getItem(KEY))||structuredClone(sample)}catch{return structuredClone(sample)}}
function save(){localStorage.setItem(KEY,JSON.stringify(data));renderAll()}
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
function toast(msg){const t=$("#toast");t.textContent=msg;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),1800)}
function letter(n){return n>=93?"A":n>=90?"A−":n>=87?"B+":n>=83?"B":n>=80?"B−":n>=77?"C+":n>=73?"C":n>=70?"C−":n>=67?"D+":n>=63?"D":n>=60?"D−":"F"}
function gp(n){return n>=93?4:n>=90?3.7:n>=87?3.3:n>=83?3:n>=80?2.7:n>=77?2.3:n>=73?2:n>=70?1.7:n>=67?1.3:n>=63?1:n>=60?.7:0}
function gpa(){let c=0,p=0;data.courses.filter(x=>x.status!=="planned").forEach(x=>{c+=+x.credits;p+=gp(+x.grade)*+x.credits});return c?(p/c).toFixed(2):"0.00"}
function attendancePct(a){const total=a.attended+a.missed;return total?Math.round(a.attended/total*100):100}
function globalAttendance(){const vals=data.courses.map(c=>data.attendance[c.id]||{attended:0,missed:0});let a=0,m=0;vals.forEach(x=>{a+=x.attended;m+=x.missed});return a+m?Math.round(a/(a+m)*100):100}
function setPage(name){$$('.page').forEach(x=>x.classList.toggle('active',x.id===name+'-page'));$$('.nav-link').forEach(x=>x.classList.toggle('active',x.dataset.page===name));$('#page-title').textContent=$(`[data-page="${name}"] span`).textContent;location.hash=name;$('#sidebar').classList.remove('open');$$('.bottom-link').forEach(x=>x.classList.toggle('active',x.dataset.mobilePage===name))}
$$('.nav-link').forEach(b=>b.onclick=()=>setPage(b.dataset.page));$$('[data-open]').forEach(b=>b.onclick=()=>setPage(b.dataset.open));$('#mobile-menu').onclick=()=>$('#sidebar').classList.toggle('open');$$('[data-mobile-page]').forEach(b=>b.onclick=()=>setPage(b.dataset.mobilePage));
function stat(label,value,sub){return `<article class="stat"><span>${esc(label)}</span><b>${esc(value)}</b><span>${esc(sub)}</span></article>`}
function summary(label,value,sub){return `<article class="summary"><span>${esc(label)}</span><b>${esc(value)}</b><span>${esc(sub)}</span></article>`}
function renderDashboard(){const pending=data.assignments.filter(a=>a.status!=="completed").length;$('#dashboard-stats').innerHTML=stat('Semester GPA',gpa(),'Estimated')+stat('Assignments',pending,'Not completed')+stat('Attendance',globalAttendance()+'%','All courses')+stat('Goals',data.goals.length,'Active targets');$('#dashboard-courses').innerHTML=data.courses.filter(c=>c.status==='current').slice(0,4).map(c=>`<div class="list-row"><div><b>${esc(c.code)} · ${esc(c.name)}</b><small>${c.credits} credits · ${esc(c.days)}</small></div><b>${letter(c.grade)} · ${c.grade}%</b></div>`).join('')||'<div class="empty">No current courses.</div>';$('#dashboard-deadlines').innerHTML=data.assignments.filter(a=>a.status!=="completed").sort((a,b)=>a.due.localeCompare(b.due)).slice(0,5).map(a=>`<div class="list-row"><div><b>${esc(a.title)}</b><small>${esc(a.course)}</small></div><b>${esc(a.due)}</b></div>`).join('')||'<div class="empty">No upcoming work.</div>'}
function renderCourses(){const q=$('#course-search').value.toLowerCase();const list=data.courses.filter(c=>(courseFilter==='all'||c.status===courseFilter)&&(c.name+' '+c.code).toLowerCase().includes(q));const credits=data.courses.filter(c=>c.status==='current').reduce((s,c)=>s+(+c.credits),0);$('#course-summary').innerHTML=summary('Total Courses',data.courses.length,'All statuses')+summary('Credits Enrolled',credits,'Current courses')+summary('Semester GPA',gpa(),'Estimated')+summary('Course Load',credits>=12?'Full-time':'Part-time',credits+' credits');$('#course-grid').innerHTML=list.map(c=>`<article class="course-card" style="--accent:${courseColors[data.courses.indexOf(c)%courseColors.length]}"><div class="course-head"><span class="badge">${esc(c.status)}</span><b>${esc(c.code)}</b></div><h3>${esc(c.name)}</h3><div class="meta"><span>📍 ${esc(c.location)}</span><span>🕘 ${esc(c.days)} · ${esc(c.time)}</span><span>🎓 ${c.credits} credit hours</span></div><div class="course-head"><span>Grade: <b>${letter(c.grade)}</b></span><b>${c.grade}%</b></div><div class="progress"><i style="width:${Math.max(0,Math.min(100,c.grade))}%"></i></div><div class="card-actions"><button class="secondary" onclick="editCourse(${c.id})">Edit</button><button class="delete" onclick="removeItem('courses',${c.id})">Delete</button></div></article>`).join('')||'<div class="panel empty">No courses found.</div>'}
function computedStatus(a){if(a.status==='completed')return 'completed';const today=new Date().toISOString().slice(0,10);return a.due<today?'overdue':'upcoming'}
function renderAssignments(){const q=$('#assignment-search').value.toLowerCase();const list=data.assignments.filter(a=>{const s=computedStatus(a);return (assignmentFilter==='all'||s===assignmentFilter)&&(a.title+' '+a.course).toLowerCase().includes(q)});const complete=data.assignments.filter(a=>a.status==='completed').length, overdue=data.assignments.filter(a=>computedStatus(a)==='overdue').length;$('#assignment-summary').innerHTML=summary('Total',data.assignments.length,'All assignments')+summary('Upcoming',data.assignments.length-complete-overdue,'Not yet due')+summary('Completed',complete,'Finished')+summary('Overdue',overdue,'Needs attention');$('#assignment-table').innerHTML=list.map(a=>{const s=computedStatus(a);return `<tr><td><b>${esc(a.title)}</b></td><td>${esc(a.course)}</td><td>${esc(a.due)}</td><td>${a.points}</td><td class="status-${s}">${s}</td><td><button class="secondary" onclick="toggleAssignment(${a.id})">${a.status==='completed'?'Reopen':'Complete'}</button> <button class="delete" onclick="removeItem('assignments',${a.id})">×</button></td></tr>`}).join('')||'<tr><td colspan="6" class="empty">No assignments found.</td></tr>'}
function renderGrades(){const credits=data.courses.reduce((s,c)=>s+(+c.credits),0);$('#grade-summary').innerHTML=summary('Semester GPA',gpa(),'Estimated')+summary('Credits',credits,'Tracked')+summary('Highest Grade',data.courses.length?Math.max(...data.courses.map(c=>+c.grade))+'%':'—','Current best')+summary('Academic Standing',+gpa()>=2?'Good':'Review','Prototype estimate');$('#grade-table').innerHTML=data.courses.map(c=>`<tr><td><b>${esc(c.code)}</b><br>${esc(c.name)}</td><td>${c.credits}</td><td>${c.grade}%</td><td><b>${letter(c.grade)}</b></td><td>${gp(c.grade).toFixed(1)}</td></tr>`).join('')}
function renderAttendance(){let attended=0,missed=0;data.courses.forEach(c=>{const a=data.attendance[c.id]||{attended:0,missed:0};attended+=a.attended;missed+=a.missed});$('#attendance-summary').innerHTML=summary('Overall',globalAttendance()+'%','Attendance rate')+summary('Attended',attended,'Meetings')+summary('Missed',missed,'Meetings')+summary('Tracked Courses',data.courses.length,'Total');$('#attendance-grid').innerHTML=data.courses.map(c=>{const a=data.attendance[c.id]||{attended:0,missed:0},p=attendancePct(a);return `<article class="attendance-card" style="--accent:${courseColors[data.courses.indexOf(c)%courseColors.length]}"><span class="badge">${esc(c.code)}</span><h3>${esc(c.name)}</h3><p>${a.attended} attended · ${a.missed} missed</p><div class="course-head"><span>Attendance</span><b>${p}%</b></div><div class="progress"><i style="width:${p}%;background:${p<75?'var(--red)':'var(--green)'}"></i></div></article>`}).join('')||'<div class="panel empty">Add a course first.</div>'}
function renderSchedule(){$('#schedule-list').innerHTML=data.courses.filter(c=>c.status==='current').map(c=>`<div class="list-row"><div><b>${esc(c.code)} · ${esc(c.name)}</b><small>${esc(c.location)}</small></div><div><b>${esc(c.days)}</b><small>${esc(c.time)}</small></div></div>`).join('')||'<div class="empty">No scheduled courses.</div>'}
function renderExams(){$('#exam-list').innerHTML=data.exams.map(x=>`<div class="list-row"><div><b>${esc(x.title)}</b><small>${esc(x.course)}</small></div><div><b>${esc(x.date)}</b> <button class="delete" onclick="removeItem('exams',${x.id})">×</button></div></div>`).join('')||'<div class="empty">No exams added.</div>'}
function renderGoals(){$('#goal-grid').innerHTML=data.goals.map(g=>`<article class="goal-card" style="--accent:${courseColors[data.goals.indexOf(g)%courseColors.length]}"><span class="badge">Goal</span><h3>${esc(g.title)}</h3><div class="course-head"><span>Progress</span><b>${g.progress}%</b></div><div class="progress"><i style="width:${g.progress}%;background:var(--purple)"></i></div><div class="card-actions"><button class="delete" onclick="removeItem('goals',${g.id})">Delete</button></div></article>`).join('')||'<div class="panel empty">No goals added.</div>'}

function minsText(n){const h=Math.floor(n/60),m=n%60;return h?`${h}h ${m}m`:`${m}m`}
function weekMinutes(){const now=new Date(),start=new Date(now);start.setDate(now.getDate()-6);return data.studySessions.filter(s=>new Date(s.date)>=start).reduce((t,s)=>t+(+s.minutes),0)}
function renderPriorities(){const overdue=data.assignments.filter(a=>computedStatus(a)==='overdue').length,upcoming=data.assignments.filter(a=>computedStatus(a)==='upcoming').length,low=data.courses.filter(c=>+c.grade<75).length;$('#priority-strip').innerHTML=`<div class="priority-item"><i>!</i><div><strong>${overdue} overdue</strong><span>${overdue?'Needs attention':'You are caught up'}</span></div></div><div class="priority-item"><i>▤</i><div><strong>${upcoming} upcoming</strong><span>Open assignments</span></div></div><div class="priority-item"><i>↗</i><div><strong>${low} at-risk courses</strong><span>Below 75 percent</span></div></div>`}
function renderStudy(){const total=data.studySessions.reduce((t,s)=>t+(+s.minutes),0),week=weekMinutes(),avg=data.studySessions.length?Math.round(total/data.studySessions.length):0;$('#study-summary').innerHTML=summary('Total Study Time',minsText(total),'All logged sessions')+summary('Last 7 Days',minsText(week),'Recent focus')+summary('Sessions',data.studySessions.length,'Logged')+summary('Average Session',minsText(avg),'Per session');$('#study-list').innerHTML=[...data.studySessions].sort((a,b)=>b.date.localeCompare(a.date)).map(s=>`<div class="list-row"><div><b>${esc(s.course)} · ${esc(s.topic)}</b><small>${esc(s.date)} · ${esc(s.method)}</small></div><div><span class="study-duration">${minsText(+s.minutes)}</span> <button class="delete" onclick="removeItem('studySessions',${s.id})">×</button></div></div>`).join('')||'<div class="empty">No study sessions yet.</div>';const grouped={};data.studySessions.forEach(s=>grouped[s.course]=(grouped[s.course]||0)+(+s.minutes));const max=Math.max(1,...Object.values(grouped));$('#study-distribution').innerHTML=Object.entries(grouped).sort((a,b)=>b[1]-a[1]).map(([c,m])=>`<div class="distribution-row"><div><b>${esc(c)}</b><span>${minsText(m)}</span></div><div class="metric-track"><div class="metric-fill" style="width:${m/max*100}%"></div></div></div>`).join('')||'<div class="empty">Log study time to see distribution.</div>'}
function renderDegree(){const completed=data.requirements.reduce((t,r)=>t+(+r.completed),0),required=data.degreeCredits||120,p=Math.min(100,Math.round(completed/required*100));$('#degree-summary').innerHTML=summary('Degree Progress',p+'%',completed+' of '+required+' credits')+summary('Credits Completed',completed,'Tracked requirements')+summary('Credits Remaining',Math.max(0,required-completed),'Estimated')+summary('Requirements',data.requirements.length,'Categories');$('#degree-table').innerHTML=data.requirements.map(r=>{const rp=Math.min(100,Math.round((+r.completed)/(+r.credits)*100));return `<tr><td><b>${esc(r.title)}</b></td><td>${esc(r.category)}</td><td>${r.credits}</td><td>${r.completed}</td><td><div class="degree-progress"><div class="ring" style="--p:${rp}"><b>${rp}%</b></div></div></td><td><button class="delete" onclick="removeItem('requirements',${r.id})">×</button></td></tr>`}).join('')||'<tr><td colspan="6" class="empty">No requirements added.</td></tr>'}
function renderAnalytics(){const complete=data.assignments.filter(a=>a.status==='completed').length,overdue=data.assignments.filter(a=>computedStatus(a)==='overdue').length,total=data.assignments.length;$('#analytics-summary').innerHTML=summary('GPA',gpa(),'Estimated')+summary('Attendance',globalAttendance()+'%','Overall')+summary('Study Time',minsText(data.studySessions.reduce((t,s)=>t+(+s.minutes),0)),'Logged')+summary('Completion Rate',total?Math.round(complete/total*100)+'%':'100%','Assignments');$('#grade-bars').innerHTML=data.courses.map((c,i)=>`<div class="metric-row"><div><b>${esc(c.code)}</b><small>${esc(c.name)}</small></div><div class="metric-track"><div class="metric-fill" style="width:${c.grade}%;background:${courseColors[i%courseColors.length]}"></div></div><b>${c.grade}%</b></div>`).join('')||'<div class="empty">No course data.</div>';const statuses=[['Completed',complete,'var(--green)'],['Upcoming',data.assignments.filter(a=>computedStatus(a)==='upcoming').length,'var(--navy)'],['Overdue',overdue,'var(--red)']];const mx=Math.max(1,...statuses.map(x=>x[1]));$('#workload-chart').innerHTML=statuses.map(x=>`<div class="metric-row"><b>${x[0]}</b><div class="metric-track"><div class="metric-fill" style="width:${x[1]/mx*100}%;background:${x[2]}"></div></div><b>${x[1]}</b></div>`).join('');const insights=[];if(overdue)insights.push(['!','Catch up on overdue work',`${overdue} assignment${overdue===1?' is':'s are'} overdue. Prioritize the closest deadline first.`]);if(globalAttendance()<85)insights.push(['✓','Attendance needs attention',`Overall attendance is ${globalAttendance()}%. Review missed meetings by course.`]);const low=data.courses.filter(c=>+c.grade<75);if(low.length)insights.push(['↗','Course performance alert',`${low.map(c=>c.code).join(', ')} ${low.length===1?'is':'are'} below 75%. Add focused study sessions.`]);if(weekMinutes()<120)insights.push(['◷','Increase focused study time',`Only ${minsText(weekMinutes())} was logged in the last seven days. Consider scheduling two focused sessions.`]);if(!insights.length)insights.push(['★','Everything looks on track','No major academic risks are currently detected from the information entered.']);$('#insights').innerHTML=insights.map(i=>`<div class="insight"><div class="insight-icon">${i[0]}</div><div><b>${i[1]}</b><p>${i[2]}</p></div></div>`).join('')}

let calendarDate=new Date(2026,7,1), selectedCalendarDate='2026-08-31', calendarFilter='all';
const eventColors={assignment:'#d94d67',exam:'#7650c7',academic:'#176bd6',personal:'#159a63'};
function dateOnly(d){return new Date(d+'T12:00:00')}
function expandRecurringEvent(e){const recurrence=e.recurrence||'none';if(recurrence==='none'||!e.repeatUntil)return [{...e}];const out=[],end=dateOnly(e.repeatUntil);let current=dateOnly(e.date),guard=0;while(current<=end&&guard<400){const day=current.getDay();if(recurrence!=='weekdays'||(day!==0&&day!==6))out.push({...e,id:e.id+'-'+current.toISOString().slice(0,10),sourceId:e.id,date:current.toISOString().slice(0,10),occurrence:true});if(recurrence==='daily'||recurrence==='weekdays')current.setDate(current.getDate()+1);else if(recurrence==='weekly')current.setDate(current.getDate()+7);else if(recurrence==='biweekly')current.setDate(current.getDate()+14);else if(recurrence==='monthly')current.setMonth(current.getMonth()+1);guard++}return out}
function allCalendarEvents(){return [
...data.assignments.map(a=>({id:'a-'+a.id,sourceId:a.id,title:a.title,date:a.due,type:'assignment',details:a.course+' · '+a.points+' points'})),
...data.exams.map(x=>({id:'x-'+x.id,sourceId:x.id,title:x.title,date:x.date,type:'exam',details:x.course})),
...data.academicDates.map(x=>({...x,details:x.category||'Official academic date'})),
...data.events.flatMap(x=>expandRecurringEvent({...x,details:[x.location,x.notes].filter(Boolean).join(' · ')}))];}
function filteredCalendarEvents(){return allCalendarEvents().filter(e=>calendarFilter==='all'||e.type===calendarFilter)}
function eventRow(e,allowDelete=false){return `<div class="event-row" style="--event-color:${eventColors[e.type]}"><i class="event-dot"></i><div><b>${esc(e.title)}</b><small>${esc(e.type[0].toUpperCase()+e.type.slice(1))}${e.recurrence&&e.recurrence!=='none'?' · ↻ '+esc(e.recurrence):''}${e.details?' · '+esc(e.details):''}</small></div>${allowDelete&&e.type==='personal'?`<button class="delete" onclick="removeItem('events',${e.sourceId||e.id})" title="Delete event series">×</button>`:''}</div>`}
function renderCalendar(){const y=calendarDate.getFullYear(),m=calendarDate.getMonth();$('#calendar-title').textContent=new Intl.DateTimeFormat('en-US',{month:'long',year:'numeric'}).format(calendarDate);const first=new Date(y,m,1),start=new Date(y,m,1-first.getDay()),today=new Date().toISOString().slice(0,10),events=filteredCalendarEvents();let html='';for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);const iso=d.toISOString().slice(0,10),dayEvents=events.filter(e=>e.date===iso),chips=dayEvents.slice(0,3).map(e=>`<span class="calendar-chip" style="--chip-bg:${eventColors[e.type]}1f;--chip-color:${eventColors[e.type]}">${esc(e.title)}</span>`).join('');html+=`<button class="calendar-day ${d.getMonth()!==m?'muted':''} ${iso===today?'today':''} ${iso===selectedCalendarDate?'selected':''}" data-date="${iso}"><span class="day-number">${d.getDate()}</span><span class="day-events">${chips}${dayEvents.length>3?`<span class="calendar-more">+${dayEvents.length-3} more</span>`:''}</span></button>`}$('#calendar-grid').innerHTML=html;$$('.calendar-day').forEach(b=>b.onclick=()=>{selectedCalendarDate=b.dataset.date;renderCalendar()});const selected=events.filter(e=>e.date===selectedCalendarDate);$('#selected-date-title').textContent=new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',year:'numeric'}).format(dateOnly(selectedCalendarDate));$('#selected-date-events').innerHTML=selected.map(e=>eventRow(e,true)).join('')||'<div class="empty">Nothing scheduled.</div>';const todayIso=new Date().toISOString().slice(0,10);$('#calendar-upcoming').innerHTML=events.filter(e=>e.date>=todayIso).sort((a,b)=>a.date.localeCompare(b.date)).slice(0,6).map(e=>`<div class="event-row" style="--event-color:${eventColors[e.type]}"><i class="event-dot"></i><div><b>${esc(e.title)}</b><small>${esc(e.date)} · ${esc(e.type)}</small></div></div>`).join('')||'<div class="empty">No upcoming events.</div>'}
function exportICS(){const lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Rocket Academic Tracker//EN','CALSCALE:GREGORIAN'];allCalendarEvents().forEach(e=>{lines.push('BEGIN:VEVENT','UID:'+e.id+'@rocket-tracker','DTSTART;VALUE=DATE:'+e.date.replaceAll('-',''),'SUMMARY:'+String(e.title).replace(/[,;]/g,' '),'DESCRIPTION:'+String(e.details||e.type).replace(/[,;]/g,' '),'END:VEVENT')});lines.push('END:VCALENDAR');const blob=new Blob([lines.join('\r\n')],{type:'text/calendar'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='rocket-academic-calendar.ics';a.click();URL.revokeObjectURL(a.href)}

function renderSemesterSelector(){const s=$('#semester-select');if(!s)return;const current=s.value;s.innerHTML='<option value="custom">Current month</option>'+data.semesters.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('');s.value=data.semesters.some(x=>x.id===current)?current:'custom'}
function selectSemester(id){const sem=data.semesters.find(x=>x.id===id);if(!sem)return;calendarDate=dateOnly(sem.start);selectedCalendarDate=sem.start;renderCalendar()}
function initials(name){return String(name||'Student').split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()}
function renderProfile(){const p=data.profile||{},init=initials(p.name);$('#profile-avatar-initials').textContent=init;$('#settings-profile-initials').textContent=init;$('#profile-display-name').textContent=p.name||'Student';$('#profile-display-details').textContent=[p.program,p.school].filter(Boolean).join(' · ');const imgs=[$('#profile-avatar-image'),$('#settings-profile-image')];imgs.forEach(img=>{if(p.picture){img.src=p.picture;img.hidden=false}else{img.removeAttribute('src');img.hidden=true}});$('#profile-avatar-initials').hidden=!!p.picture;$('#settings-profile-initials').hidden=!!p.picture}
function resizeProfilePicture(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=reject;reader.onload=()=>{const img=new Image();img.onerror=reject;img.onload=()=>{const size=320,canvas=document.createElement('canvas');canvas.width=canvas.height=size;const ctx=canvas.getContext('2d'),scale=Math.max(size/img.width,size/img.height),w=img.width*scale,h=img.height*scale;ctx.drawImage(img,(size-w)/2,(size-h)/2,w,h);resolve(canvas.toDataURL('image/jpeg',.84))};img.src=reader.result};reader.readAsDataURL(file)})}
function renderAll(){renderDashboard();renderPriorities();renderCourses();renderAssignments();renderGrades();renderAttendance();renderStudy();renderDegree();renderAnalytics();renderSemesterSelector();renderProfile();renderCalendar();renderSchedule();renderExams();renderGoals();if(document.activeElement!==$('#notes'))$('#notes').value=data.notes||'';document.body.classList.toggle('dark',data.theme==='dark')}
$('#course-search').oninput=renderCourses;$('#assignment-search').oninput=renderAssignments;$$('#course-filters button').forEach(b=>b.onclick=()=>{$$('#course-filters button').forEach(x=>x.classList.remove('active'));b.classList.add('active');courseFilter=b.dataset.filter;renderCourses()});$$('#assignment-filters button').forEach(b=>b.onclick=()=>{$$('#assignment-filters button').forEach(x=>x.classList.remove('active'));b.classList.add('active');assignmentFilter=b.dataset.filter;renderAssignments()});


$('#semester-select').onchange=e=>{if(e.target.value==='custom'){calendarDate=new Date();selectedCalendarDate=new Date().toISOString().slice(0,10);renderCalendar()}else selectSemester(e.target.value)};
$('#profile-avatar').onclick=()=>setPage('settings');
$('#profile-photo-button').onclick=()=>$('#profile-picture-input').click();
$('#edit-profile').onclick=()=>openModal('profile',data.profile);
$('#remove-profile-picture').onclick=()=>{data.profile.picture='';save();toast('Profile picture removed')};
$('#profile-picture-input').onchange=async e=>{const file=e.target.files[0];if(!file)return;if(file.size>8*1024*1024){alert('Please choose an image smaller than 8 MB.');return}try{data.profile.picture=await resizeProfilePicture(file);save();toast('Profile picture updated')}catch{alert('The selected picture could not be processed.')}e.target.value=''};
$('#calendar-prev').onclick=()=>{calendarDate.setMonth(calendarDate.getMonth()-1);renderCalendar()};
$('#calendar-next').onclick=()=>{calendarDate.setMonth(calendarDate.getMonth()+1);renderCalendar()};
$('#calendar-today').onclick=()=>{calendarDate=new Date();selectedCalendarDate=new Date().toISOString().slice(0,10);renderCalendar()};
$('#export-calendar').onclick=exportICS;
$$('#calendar-filters button').forEach(b=>b.onclick=()=>{$$('#calendar-filters button').forEach(x=>x.classList.remove('active'));b.classList.add('active');calendarFilter=b.dataset.calendarFilter;renderCalendar()});
$('#notes').oninput=e=>{data.notes=e.target.value;localStorage.setItem(KEY,JSON.stringify(data))};
function removeItem(type,id){if(!confirm('Delete this item?'))return;data[type]=data[type].filter(x=>x.id!==id);if(type==='courses')delete data.attendance[id];save();toast('Deleted')}
function toggleAssignment(id){const a=data.assignments.find(x=>x.id===id);a.status=a.status==='completed'?'upcoming':'completed';save();toast('Assignment updated')}
const modal=$('#modal'), fields=$('#modal-fields'), form=$('#modal-form');let modalType='',editingId=null;
const schemas={course:[['code','Course code','text'],['name','Course name','text'],['credits','Credits','number'],['status','Status','select','current|planned|completed'],['grade','Percentage','number'],['days','Meeting days','text'],['time','Time','time'],['location','Location','text']],assignment:[['title','Assignment title','text'],['course','Course code','text'],['due','Due date','date'],['points','Points','number']],attendance:[['courseId','Course','course'],['result','Result','select','attended|missed']],exam:[['title','Exam title','text'],['course','Course code','text'],['date','Date','date']],goal:[['title','Goal','text'],['progress','Progress percent','number']],study:[['course','Course code','text'],['date','Date','date'],['minutes','Minutes','number'],['method','Study method','text'],['topic','Topic','text']],requirement:[['title','Requirement','text'],['category','Category','select','Core|Major|Minor|Elective|Other'],['credits','Credits required','number'],['completed','Credits completed','number']],event:[['title','Event title','text'],['date','First date','date'],['location','Location','text'],['notes','Details','text'],['recurrence','Repeats','select','none|daily|weekdays|weekly|biweekly|monthly'],['repeatUntil','Repeat until','date']],profile:[['name','Display name','text'],['school','School','text'],['program','Program or major','text']]};
function fieldHtml(f,val=''){const [name,label,type,options]=f;if(type==='select')return `<div class="field"><label>${label}</label><select name="${name}">${options.split('|').map(x=>`<option ${x===val?'selected':''}>${x}</option>`).join('')}</select></div>`;if(type==='course')return `<div class="field"><label>${label}</label><select name="${name}">${data.courses.map(c=>`<option value="${c.id}">${esc(c.code)} · ${esc(c.name)}</option>`).join('')}</select></div>`;return `<div class="field"><label>${label}</label><input required name="${name}" type="${type}" value="${esc(val)}" ${type==='number'?'min="0"':''}></div>`}
function openModal(type,item=null){modalType=type;editingId=item?.id||null;$('#modal-title').textContent=(item?'Edit ':'Add ')+type[0].toUpperCase()+type.slice(1);fields.innerHTML=schemas[type].map(f=>fieldHtml(f,item?.[f[0]]??'')).join('');modal.showModal()}
$$('[data-modal]').forEach(b=>b.onclick=()=>openModal(b.dataset.modal));
window.editCourse=id=>openModal('course',data.courses.find(c=>c.id===id));window.removeItem=removeItem;window.toggleAssignment=toggleAssignment;
form.addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return;e.preventDefault();const v=Object.fromEntries(new FormData(form));if(modalType==='attendance'){const id=+v.courseId;data.attendance[id]??={attended:0,missed:0};data.attendance[id][v.result]++;}else{if(modalType==='profile'){data.profile={...data.profile,...v};modal.close();save();toast('Profile updated');return}const map={course:'courses',assignment:'assignments',exam:'exams',goal:'goals',study:'studySessions',requirement:'requirements',event:'events'},arr=data[map[modalType]];const item={...v,id:editingId||Date.now()};['credits','grade','points','progress','minutes','completed'].forEach(k=>{if(k in item)item[k]=+item[k]});if(modalType==='assignment')item.status='upcoming';if(modalType==='event'){item.type='personal';item.recurrence||='none';if(item.recurrence==='none')item.repeatUntil=''}if(editingId){const i=arr.findIndex(x=>x.id===editingId);arr[i]=item}else arr.push(item)}modal.close();save();toast('Saved')});
function toggleTheme(){data.theme=data.theme==='dark'?'light':'dark';save()}$('#theme-toggle').onclick=toggleTheme;$('#settings-theme').onclick=toggleTheme;
$('#export-data').onclick=()=>{const b=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='rocket-tracker-backup.json';a.click();URL.revokeObjectURL(a.href)};
$('#import-data').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{data=JSON.parse(r.result);save();toast('Backup imported')}catch{alert('That file is not a valid tracker backup.')}};r.readAsText(f)};
$('#reset-data').onclick=()=>{if(confirm('Reset all local tracker data?')){data=structuredClone(sample);save();toast('Prototype reset')}};
const start=location.hash.slice(1);if(start&&$(`#${start}-page`))setPage(start);renderAll();